status         =  { "x" | " " }
priority       =  { "(" ~ priority_inner ~ ")" }
priority_inner = @{ "low" | "medium" | "high" }
tag_inner      = @{ (!" " ~ !NEWLINE ~ ANY)+ }
tag            =  { "#" ~ tag_inner }

description_text = @{
    (!(NEWLINE) ~ !(" " ~ "(") ~ !(" " ~ "#") ~ ANY)+
}

task_line = {
    "-" ~ " " ~ "[" ~ status ~ "]" ~ " " ~ description_text ~ (" " ~ priority)? ~ (" " ~ tag)* ~ (NEWLINE | EOI)
}

file = {
    SOI ~ (task_line | NEWLINE)* ~ EOI
}
